mysql2: &mysql2
  adapter: mysql2
  encoding: utf8

development: &development
  <<: *mysql2
  host:     <%= ENV['BRAVO_COLLECTION_DB_HOST']     %>
  database: <%= ENV['BRAVO_COLLECTION_DB_DATABASE'] %>
  username: <%= ENV['BRAVO_COLLECTION_DB_USER']     %>
  password: <%= ENV['BRAVO_COLLECTION_DB_PASSWORD'] %>
  min_messages: warning
  pool: 2
  timeout: 5000

production:
  <<: *mysql2
  host:     <%= ENV['BRAVO_COLLECTION_DB_HOST']     %>
  database: <%= ENV['BRAVO_COLLECTION_DB_DATABASE'] %>
  username: <%= ENV['BRAVO_COLLECTION_DB_USER']     %>
  password: <%= ENV['BRAVO_COLLECTION_DB_PASSWORD'] %>
